### ISSUE TITLE
Tensorflow implementation

### ISSUE THREAD

**Issue by AlfredUg** [unnir/CancelOut#2]
Heya,

Good job here. Inquiring about the Tensorflow/Keras implementation of CancelOut.

Thanks,
Alfred.

**Comment by unnir** [comment]
will do it, thank you for your request!

**Comment by unnir** [comment]
Thank you once again, 

the CancelOut Keras/TensorFlow implementation is available now. Please check the README.md or have a look at this notebook: https://github.com/unnir/CancelOut/blob/master/keras_example.ipynb
